### ISSUE TITLE
Minor mode icons missing

### ISSUE THREAD

**Issue by rupakraj** [rhoit/powerline-iconic-theme#1]
Hello ! I was trying the theme for minor mode icons
But it shows something like this. It seems you missed to add some icons.

![selection_026](https://cloud.githubusercontent.com/assets/1549123/12135782/2e1a3236-b468-11e5-9009-230ae8829509.png)

**Comment by rhoit** [comment]
@rupakraj please update the your https://github.com/rhoit/mode-icons
and make sure to change the path. currently its pointing to "~/.emacs.d/00testing/mode-icons/icons/"
which may not be correct in your case. will update this package later, for more recent changes see
https://github.com/rhoit/dot-emacs/blob/master/config/modeline.cfg.el
